# Generated by Django 3.0.8 on 2020-09-17 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200917_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='bird',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Bird'),
            preserve_default=False,
        ),
    ]
